# Default values for ISECL-SCHEDULER.

nameOverride: "" # The name for ISECL-SCHEDULER chart<br> (Default: `.Chart.Name`)
controlPlaneLabel: 10.105.167.197 #K8s control plane label<br> (**REQUIRED**)<br> Example: `node-role.kubernetes.io/master` in case of `kubeadm`/`microk8s.io/cluster` in case of `microk8s`

dependentServices: # The dependent Service Name for deploying  ISECL-SCHEDULER chart, default is the chart name and override is from nameOverride value.
  ihub: ihub
  
image:
  svc:
    registry: 10.105.168.18:5000 # The image registry where ISECL-SCHEDULER image is pushed<br> (**REQUIRED**)
    name: isecl-scheduler # The image name with which ISECL-SCHEDULER image is pushed to registry<br> (**REQUIRED**)
    pullPolicy: Always  # The pull policy for pulling from container registry for ISECL-SCHEDULER<br> (Allowed values: `Always`/`IfNotPresent`)

securityContext:
  init: # The fsGroup id for init containers
    fsGroup: 1001 
  iseclScheduler: # The security content for ISECL-SCHEDULER Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false

service: 
  directoryName: isecl-k8s-extensions
  containerPort: 8888 # The containerPort on which CMS can listen to traffic
  port: 30888 # The externally exposed NodePort on which CMS can listen to external traffic

    