{{- include "factory.headers" . }}
{{- if .Values.config.tpmOwnerSecret }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "factory.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  TPM_OWNER_SECRET: {{ .Values.config.tpmOwnerSecret }}
{{- end }}