{{- include "factory.headers" . }}
---
{{- include "factory.deploymentCommonSpec" . }}
    spec:
      initContainers:
        {{- include "factory.initCommonSpecLinkServiceVolumes" . | nindent 8 }}
          securityContext:
            {{- toYaml .Values.securityContext.cms | nindent 12 }}
          volumeMounts:
            {{- include "factory.volumeMountsBasePv" . | nindent 12 }}
      containers:
        - name: {{ include "factory.name" . }}
          {{- include "factory.imageContainer" . | indent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext.cms | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.cms.containerPort }}
          readinessProbe:
            httpGet:
              path: /cms/v1/version
              port: {{ .Values.service.cms.containerPort }}
              scheme: HTTPS            
            initialDelaySeconds: 1
            failureThreshold: 30
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: {{ include "factory.name" . }}
          volumeMounts:
            {{- include "factory.volumeMountSvcConfig" . | nindent 12 }}
            {{- include "factory.volumeMountSvcLogs" . | nindent 12 }}
      volumes:
        {{- include "factory.volumeSvcConfig" . | nindent 8 }}
        {{- include "factory.volumeSvcLogs" . | nindent 8 }}
        {{- include "factory.volumesBasePV" . | nindent 8 }}