# Default values for tcs.

nameOverride: "" # The name for TCS chart<br> (Default: `.Chart.Name`)
controlPlaneHostname: <user input> # K8s control plane IP/Hostname<br> (**REQUIRED**)

# Warning: Ensure that the naming is applied consistently for all dependent services when modifying nameOverride
# TODO: Services should be be able to be deployed in different namespaces
dependentServices: # The dependent Service Name for deploying  TEE Caching Service chart, default is the chart name and override is from nameOverride value.
  cms: cms
  aas: aas

config:
  envVarPrefix: TCS
  dbPort: 5432 # PostgreSQL DB port
  dbSSL: on # PostgreSQL DB SSL<br> (Allowed: `on`/`off`)
  #TODO: to remove the below values if hardcoding the path
  dbSSLCert: /etc/postgresql/secrets/server.crt # PostgreSQL DB SSL Cert
  dbSSLKey: /etc/postgresql/secrets/server.key # PostgreSQL DB SSL Key
  dbSSLCiphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256 # PostgreSQL DB SSL Ciphers
  dbListenAddresses: "*" # PostgreSQL DB Listen Address
  dbName: tcsdb # TCS DB Name
  dbSSLMode: verify-full # PostgreSQL DB SSL Mode
  intelPcsUrl: https://sbx.api.trustedservices.intel.com/sgx/certification/v4  # Intel PCS URL
  retryCount: 3 # Retries attempted in case PCS is not responding
  waitTime: 1 # Time interval between each retry in seconds
  refreshInterval: 6 # Automatic refresh time of platform collateral

secret:
  dbUsername: tcsdbuser # DB Username for TCS DB
  dbPassword: tcsdbpassword # DB Password for TCS DB
  intelPcsApiKey: <user input> # Intel PCS API Subscription Key
    
image:
  db:
    registry: dockerhub.io # The image registry where PostgreSQL image is pulled from
    name: postgres:11.7 # The image name of PostgreSQL
    pullPolicy: Always # The pull policy for pulling from container registry for PostgreSQL image<br> (Allowed values: `Always`/`IfNotPresent`)
  svc:
    registry: <user input> # The image registry where TCS image is pushed<br> (**REQUIRED**)
    name: <user input> # The image name with which TCS image is pushed to registry
    pullPolicy: Always # The pull policy for pulling from container registry for TCS<br> (Allowed values: `Always`/`IfNotPresent`)

storage:
  nfs:
    server: <user input> # The NFS Server IP/Hostname
    reclaimPolicy: Retain # The reclaim policy for NFS<br> (Allowed values: `Retain`/)
    accessModes: ReadWriteMany # The access modes for NFS<br> (Allowed values: `ReadWriteMany`)
    path: /mnt/nfs_share # The path for storing persistent data on NFS
    dbSize: 1Gi # The DB size for storing DB data for TCS in NFS path
    configSize: 10Mi # The configuration size for storing config for TCS in NFS path
    logsSize: 1Gi # The logs size for storing logs for TCS in NFS path
    baseSize: 2.1Gi # The base volume size (configSize + logSize + dbSize)

securityContext:
  tcsdbInit: # The fsGroup id for init containers for TCS DB
    fsGroup: 1001
  tcsdb: # The security content for TCS DB Service Pod
    runAsUser: 1001
    runAsGroup: 1001
  tcsInit: # The fsGroup id for init containers for TCS
    fsGroup: 1001
  tcs: # The security content for TCS Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false

service: 
  directoryName: tcs
  cms:
    containerPort: 8445 # The containerPort on which CMS can listen
    port: 30445 # The externally exposed NodePort on which CMS can listen to external traffic
  aas:
    containerPort: 8444 # The containerPort on which AAS can listen
    port: 30444 # The externally exposed NodePort on which AAS can listen to external traffic
  tcsdb:
    containerPort: 5432 # The containerPort on which TCS DB can listen
  tcs:
    containerPort: 9000 # The containerPort on which TCS can listen
    port: 30501 # The externally exposed NodePort on which TCS can listen to external traffic
