---
# The below section can be used to override additional values defined under each of the dependent charts
cms:
  image:
    name: <user input> # Certificate Management Service image name<br> (**REQUIRED**)

aas:
  image:
    name: <user input> # Authentication & Authorization Service image name<br> (**REQUIRED**)

aas-manager:
  image:
    name: <user input> # Authentication & Authorization Manager image name<br> (**REQUIRED**)

hvs:
  image:
    name: <user input> # Host Verification Service image name<br> (**REQUIRED**)

wls:
  image:
    name: <user input> # Worload Service image name<br> (**REQUIRED**)

ta: 
  image:
    name: <user input> # Trust Agent image name<br> (**REQUIRED**)

  nodeLabel: 
    txt: "" # The node label for TXT-ENABLED hosts<br> (**REQUIRED IF NODE IS TXT ENABLED**)
    suefi: "" # The node label for SUEFI-ENABLED hosts (**REQUIRED IF NODE IS SUEFI ENABLED**)

  config:
    tpmOwnerSecret: <user input> # The TPM owner secret if TPM is already owned 

wla:
  image:
    name: <user input> # Workload Agent image name<br> (**REQUIRED**)

global:
  controlPlaneHostname: <user input> # K8s control plane IP/Hostname<br> (**REQUIRED**)
  
  image:
    registry: <user input> # The image registry where isecl images are pushed<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry (Allowed values: `Always`/`IfNotPresent`)
  
  config:
    keyManager: kmip # The Key manager for KBS (Allowed values: `kmip`)
    kmip:       
      serverIp: # The KMIP server IP
      serverHostname:  # The KMIP server hostname
      serverPort: 5696 # The KMIP server port
      clientCertPath: /etc/kmip/client_certificate.pem # The KMIP server client certificate absolute path
      clientKeyPath: /etc/kmip/client_key.pem # The KMIP server client key absolute path
      rootCertPath: /etc/kmip/root_certificate.pem # The KMIP server root certificate absolute path

  storage:
    nfs:
      server: <user input> # The NFS Server IP/Hostname<br> (**REQUIRED**)
      path: /mnt/nfs_share/  # The path for storing persistent data on NFS
  
  service:
    cms: 30445 # The service port for Certificate Management Service
    aas: 30444 # The service port for Authentication Authorization Service
    hvs: 30443 # The service port for Host Verification Service
    kbs: 30448 # The service port for Key Broker Service
    wls: 30446 # The service port for Workload Service
    ta: 31443 # The service port for Trust Agent
