# Default values for aas.

nameOverride: "" # The name for FDA chart<br> (Default: `.Chart.Name`)
controlPlaneHostname: <user input> # K8s control plane IP/Hostname<br> (**REQUIRED**)
nodeLabel: 
  sgx: SGX-ENABLED # The node label for SGX-ENABLED hosts<br> (**REQUIRED IF NODE IS SGX ENABLED**)
  tdx: TDX-ENABLED # The node label for TDX-ENABLED hosts<br> (**REQUIRED IF NODE IS TDX ENABLED**)

# Warning: Ensure that the naming is applied consistently for all dependent services when modifying nameOverride
# TODO: Services should be be able to be deployed in different namespaces
dependentServices: # The dependent Service Name for deploying  Cerificate Management Service chart, default is the chart name and override is from nameOverride value.
  cms: cms
  aas: aas
  fda: fda
  tcs: tcs
    
image:
  svc:
    registry: <user input> # The image registry where FDA image is pushed<br> (**REQUIRED**)
    name: <user input> # The image name with which CMS image is pushed to registry
    pullPolicy: Always # The pull policy for pulling from container registry for AAS<br> (Allowed values: `Always`/`IfNotPresent`)

config:
  refreshInterval: <user input> #Refresh Interval
  retryCount: <user input> #Retry count
  validitySeconds: <user input> #Validity seconds

secret:
  customToken: <user input>  # Custom Token for FDA

service: 
  directoryName: fda
  cms:
    containerPort: 8445 # The containerPort on which CMS can listen
    port: 30445 # The externally exposed NodePort on which CMS can listen to external traffic
  aas:
    containerPort: 8444 # The containerPort on which AAS can listen
    port: 30444 # The externally exposed NodePort on which AAS can listen to external traffic
  fds:
    containerPort: 13000 # The containerPort on which FDS can listen
    port: 30500
  tcs:
    containerPort: 9000 # The containerPort on which TCS can listen
    port: 30501

proxy:
  http_proxy: <user input> # HTTP Proxy value
  https_proxy: <user input> # HTTP Proxy value
  no_proxy: <user input> # No Proxy value