{{- include "factory.headers" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: isecl
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: isecl
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
rules:
- apiGroups: [""]
  resources: ["pods", "secrets","configmaps"]
  verbs: ["get", "list", "create","delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: isecl
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
subjects:
- kind: ServiceAccount
  name: isecl
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: isecl
  apiGroup: rbac.authorization.k8s.io