{{- include "factory.headers" . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wlsdb-cert-generator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wlsdb-cert-generator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "wlsdb-cert-generator.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext.wlsdbCertGeneratorInit | nindent 8 }}
      serviceAccountName: isecl
      restartPolicy: Never
      containers:
        - name: wlsdb-cert-generator
          image: solsson/kubectl-cfssl:latest
          imagePullPolicy: Always
          securityContext:
            {{- toYaml .Values.securityContext.wlsdbCertGenerator | nindent 12 }}
          command: ["/bin/sh", "-c"]
          args:
            - >
              echo starting &&
              cd /tmp/ &&
              cfssl gencert -initca /tmp/certs/ca-csr.json | cfssljson -bare ca - &&
              echo '{"CN":"wlsdb TLS Certificate","hosts":["wlsdb.{{ .Release.Namespace }}.svc.cluster.local  "],"key":{"algo":"rsa","size":4096}}' | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -profile=server -hostname="wlsdb.{{ .Release.Namespace }}.svc.cluster.local" - | cfssljson -bare wlsdb-server &&
              kubectl create secret generic wlsdb-certs -n {{ .Release.Namespace }} --from-file=server.crt=wlsdb-server.pem --from-file=server.key=wlsdb-server-key.pem
          volumeMounts:
            - name: ca-csr
              mountPath: /tmp/certs
      volumes:
        - name: ca-csr
          configMap:
            name: ca-csr
