{{- include "factory.headers" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "factory.name" . }}
  namespace: {{ .Release.Namespace }}
data:
   CMS_BASE_URL: https://{{ .Values.dependentServices.cms }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.cms.containerPort }}/cms/v1
   TCS_BASE_URL: https://{{ .Values.dependentServices.tcs }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.tcs.containerPort }}/tcs/v4/sgx
   FDS_BASE_URL: https://{{ .Values.dependentServices.fds }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.fds.containerPort }}/fds/v1
   RETRY_COUNT: {{ .Values.config.retryCount }}
   REFRESH_INTERVAL: {{ .Values.config.refreshInterval }}
   VALIDITY_SECONDS: {{ .Values.config.validitySeconds }}
  {{- if .Values.global }}
   CONTROL_PLANE_IP: {{ .Values.global.controlPlaneHostname }}
  {{- else }}
   CONTROL_PLANE_IP: {{ .Values.controlPlaneHostname }}
  {{- end }}

