---
# The below section can be used to override additional values defined under each of the dependent charts
cms:
  image:
    name: <user input> # Certificate Management Service image name<br> (**REQUIRED**)

aas:
  image:
    name: <user input> # Authentication & Authorization Service image name<br> (**REQUIRED**)

aas-manager:
  image:
    name: <user input> # Authentication & Authorization Manager image name<br> (**REQUIRED**)

tcs:
  image:
    name: <user input> # TEE caching service image name<br> (**REQUIRED**)

fds:
  image:
    name: <user input> # Feature Discovery Service flow image name<br> (**REQUIRED**)

ihub:
  image:
    name: <user input> # Integration Hub Service flow image name<br> (**REQUIRED**)

isecl-controller:
  image:
    name: <user input> # Isecl Controller flow image name<br> (**REQUIRED**)

isecl-scheduler:
  image:
    name: <user input> # Isecl Scheduler flow image name<br> (**REQUIRED**)

global:
  controlPlaneHostname: <user input> # K8s control plane IP/Hostname<br> (**REQUIRED**)
  controlPlaneLabel: <user input> #K8s control plane label<br> (**REQUIRED**)<br> Example: `node-role.kubernetes.io/master` in case of `kubeadm`/`microk8s.io/cluster` in case of `microk8s`

  image:
    registry: <user input> # The image registry where isecl images are pushed<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry (Allowed values: `Always`/`IfNotPresent`)
  

  proxy: # For Feature Discovery Service HTTP Proxy details
    http_proxy: <user input> # HTTP Proxy value
    https_proxy: <user input> # HTTP Proxy value
    no_proxy: <user input> # No Proxy value

  storage:
    nfs:
      server: <user input> # The NFS Server IP/Hostname<br> (**REQUIRED**)
      path: /mnt/nfs_share/  # The path for storing persistent data on NFS

  service:
    aas: 30444 # The service port for Authentication Authorization Service
    cms: 30445 # The service port for Certificate Management Service
    fds: 30500 # The service port for Feature Discovery Service
    qvs: 30501 # The service port for Authentication Authorization Service
    tcs: 30502 # The service port for TCS Service
    isecl-scheduler: 30888 #The service port for Isecl scheduler
