{{- include "factory.headers" . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "aas-manager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aas-manager.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "aas-manager.labels" . | nindent 8 }}
    spec:
      serviceAccountName: isecl
      securityContext:
        {{- toYaml .Values.securityContext.init | nindent 8 }}
      restartPolicy: Never
      initContainers:
        - name: wait-for-aas
        {{- if .Values.global }}
          image: {{ .Values.global.image.registry }}/init-wait:{{.Chart.AppVersion }}
        {{- else }}
          image: {{ .Values.image.registry }}/init-wait:{{.Chart.AppVersion }}
        {{- end }}
          env:
            - name: URL
              value: https://{{ .Values.dependentServices.aas }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.aas.containerPort }}/aas/v1/version
            - name: VERSION
              value: {{.Chart.AppVersion }}         
            - name: DEPEDENT_SERVICE_NAME
              value: {{ .Values.dependentServices.aas }}
            - name: COMPONENT
              value: {{ include "aas-manager.name" . }}
      containers:
        - name: aas-manager
        {{- if .Values.global }}
          image: {{ .Values.global.image.registry }}/{{ .Values.image.name }}:{{.Chart.AppVersion }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        {{- else }}
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext.aasManager | nindent 12 }}
          command: ["/bin/sh", "-c"]
          #TODO: superAdmin in below command for getting bearer token should be made as template variable should be same as user mention in values.yml for install admin token
          args:
            - >
              echo starting &&
              BEARER_TOKEN=$(populate-users --use_json=true --in_json_file=/etc/secrets/populate-users.json | grep "Token for User: superAdmin" -A 2 | grep BEARER_TOKEN | cut -d '=' -f2) &&
              if [ -z "$BEARER_TOKEN" ]; then exit 1; fi  &&
              echo $BEARER_TOKEN &&
              ./kubectl create secret generic bearer-token -n {{ .Release.Namespace }} --from-literal=BEARER_TOKEN=$BEARER_TOKEN
          volumeMounts:
            - name: {{ include "aas-manager.name" . }}
              mountPath: /etc/secrets/
              readOnly: true
      volumes:
        - name: {{ include "aas-manager.name" . }}
          secret:
            secretName: {{ include "aas-manager.name" . }}
