# Copyright (C) 2021  Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aas-manager.name" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  #TODO: the aas-manager.json file needs to be updated for rest of the services
  populate-users.json: {{ tpl (.Files.Get "aas-manager.json") . | b64enc }}