# Default values for aas-manager.

nameOverride: "" # The name for AAS-MANAGER chart (Default: .Chart.Name)
controlPlaneHostname: <user input> # K8s control plane IP/Hostname

# Warning: Ensure that the naming is applied consistently for all dependent services when modifying nameOverride
# TODO: Services should be be able to be deployed in different namespaces
dependentServices: # The dependent Service Name for deploying  Cerificate Management Service chart, default is the chart name and override is from nameOverride value.
  aas: aas

image:
  registry: <user input> # The image registry where AAS-MANAGER image is pushed
  name: <user input> # The image name with which AAS-MANAGER image is pushed to registry
  pullPolicy: Always # The pull policy for pulling from container registry (Allowed values: Always/IfNotPresent)

securityContext:
  init: # The fsGroup id for init containers for AAS-MANAGER
    fsGroup: 1001
  
  aasManager: # The security content for AAS-MANAGER Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false

service:
  aas:
    containerPort: 8444 # The containerPort on which AAS can listen