apiVersion: v1
entries:
  Host-Attestation:
  - apiVersion: v2
    appVersion: v4.1.0
    created: "2022-01-19T19:27:43.644477849+05:30"
    dependencies:
    - name: factory
      repository: https://raghav19.github.io/helm-charts/charts
      version: 0.1.0
    - name: cms
      repository: https://raghav19.github.io/helm-charts/charts
      version: 0.1.0
    - name: aas
      repository: https://raghav19.github.io/helm-charts/charts
      version: 0.1.0
    - name: aas-manager
      repository: https://raghav19.github.io/helm-charts/charts
      version: 0.1.0
    - name: hvs
      repository: https://raghav19.github.io/helm-charts/charts
      version: 0.1.0
    - name: ta
      repository: https://raghav19.github.io/helm-charts/charts
      version: 0.1.0
    description: A Helm chart for Deploying ISecL-DC Platform Attestation Use case
    digest: c29687429c1a7f08c3d6c7fc893229cd07583f2ea50b5630cb13526d53706ce3
    maintainers:
    - email: johnny.jacob@intel.com
      name: JJ
    - email: praveenrajr@intel.com
      name: PraveenRaj R
    - email: raghavender.nagarajan@intel.com
      name: rana19
    name: Host-Attestation
    type: application
    urls:
    - https://raghav19.github.io/helm-charts/Host-Attestation-0.1.0.tgz
    version: 0.1.0
  aas:
  - apiVersion: v2
    appVersion: v4.1.0
    created: "2022-01-19T19:27:43.645975554+05:30"
    dependencies:
    - name: factory
      repository: https://raghav19.github.io/helm-charts/charts/
      version: 0.1.0
    description: A Helm chart for Installing ISecL-DC Authentication and Authorization
      Service
    digest: daaec28dc385ad8785c2c610104acc146bae7553edc77209642e27a9aff5896f
    name: aas
    type: application
    urls:
    - https://raghav19.github.io/helm-charts/aas-0.1.0.tgz
    version: 0.1.0
  aas-manager:
  - apiVersion: v2
    appVersion: v4.1.0
    created: "2022-01-19T19:27:43.646894996+05:30"
    dependencies:
    - name: factory
      repository: https://raghav19.github.io/helm-charts/charts
      version: 0.1.0
    description: A Helm chart for bootstrapping default users and roles and fetching
      jwt token from Authentication & Authorization Service
    digest: 17ab3ff4551daf243de6c19b3193b3bf6e60092339f8639fff45e4793b63cc06
    name: aas-manager
    type: application
    urls:
    - https://raghav19.github.io/helm-charts/aas-manager-0.1.0.tgz
    version: 0.1.0
  cms:
  - apiVersion: v2
    appVersion: v4.1.0
    created: "2022-01-19T19:27:43.647906375+05:30"
    dependencies:
    - name: factory
      repository: https://raghav19.github.io/helm-charts/
      version: 0.1.0
    description: A Helm chart for Installing ISecL-DC Certificate Management Service
    digest: dcca326c89867583de5d02054349c4824a3dcd9c670a2a2787129d12137515ae
    name: cms
    type: application
    urls:
    - https://raghav19.github.io/helm-charts/cms-0.1.0.tgz
    version: 0.1.0
  factory:
  - apiVersion: v2
    appVersion: 4.1.0
    created: "2022-01-19T19:27:43.648163639+05:30"
    description: A Helm chart for Kubernetes
    digest: ab797d233e932d432afd2cf04fad6ea1896d1ecc1080109e82b8e64257cfd372
    name: factory
    type: library
    urls:
    - https://raghav19.github.io/helm-charts/factory-0.1.0.tgz
    version: 0.1.0
  hvs:
  - apiVersion: v2
    appVersion: v4.1.0
    created: "2022-01-19T19:27:43.649004818+05:30"
    dependencies:
    - name: factory
      repository: https://raghav19.github.io/helm-charts/charts
      version: 0.1.0
    description: A Helm chart for Installing ISecL-DC Host Verification Service
    digest: 2488bc1068a4510f078e54d37b2f116da3ba2c79ad872328900d552a5732e8bc
    name: hvs
    type: application
    urls:
    - https://raghav19.github.io/helm-charts/hvs-0.1.0.tgz
    version: 0.1.0
  ta:
  - apiVersion: v2
    appVersion: v4.1.0
    created: "2022-01-19T19:27:43.649624754+05:30"
    dependencies:
    - name: factory
      repository: https://raghav19.github.io/helm-charts/charts
      version: 0.1.0
    description: A Helm chart for Installing ISecL-DC Trust Agent
    digest: b40dcdbb02b20e6e97ed134ef0d76303495b970e37c4ac6f7027a769f918ed9c
    name: ta
    type: application
    urls:
    - https://raghav19.github.io/helm-charts/ta-0.1.0.tgz
    version: 0.1.0
generated: "2022-01-19T19:27:43.640062452+05:30"
