{{- include "factory.headers" . }}
---
{{- include "factory.deploymentCommonSpec" . }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext.tcsInit | nindent 8 }}
      serviceAccountName: isecl
      initContainers:
        {{- include "factory.initWaitForDb" . | nindent 8 }}
        {{- include "factory.initWaitForCmsSha384BearerToken" . | nindent 8 }}
        {{- include "factory.initCommonSpecLinkServiceVolumes" . | nindent 8 }}
          securityContext:
            {{- toYaml .Values.securityContext.tcs | nindent 12 }}
          volumeMounts:
            {{- include "factory.volumeMountsBasePv" . | nindent 12 }}
      containers:
        - name: {{ include "factory.name" . }}
          {{- include "factory.imageContainer" . | indent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext.tcs | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "factory.name" . }}
          env:
            {{- include "factory.envCmsSha384" . | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.tcs.containerPort }}
          readinessProbe:
            httpGet:
              path: /tcs/v4/sgx
              port: {{ .Values.service.tcs.containerPort }}
              scheme: HTTPS
            initialDelaySeconds: 5
            failureThreshold: 60
            periodSeconds: 15
          volumeMounts:
          {{- include "factory.volumeMountSvcConfig" . | nindent 12 }}
          {{- include "factory.volumeMountSvcLogs" . | nindent 12 }}
          {{- include "factory.volumeMountsSvcDb" . | nindent 12 }}
          {{- include "factory.volumeMountSecrets" . | nindent 12 }}
      volumes:
      {{- include "factory.volumeSvcConfig" . | nindent 8 }}
      {{- include "factory.volumeSvcLogs" . | nindent 8 }}
      {{- include "factory.volumesSvcDb" . | nindent 8 }}
      {{- include "factory.volumesBasePV" . | nindent 8}}
      {{- include "factory.volumeProjectedSecrets" . | nindent 8 }}
      {{- include "factory.volumeCredentials" . | nindent 12 }}
      {{- include "factory.volumeAasBearerToken" . | nindent 12 }}