{{- include "factory.headers" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "factory.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  INTEL_PCS_API_KEY: {{ .Values.secret.intelPcsApiKey }}