{{- include "factory.headers" . }}
---
{{- include "factory.serviceCommonSpec" . }}
  type: NodePort
  ports:
    - port: {{ .Values.service.tcs.containerPort }}
      targetPort: {{ .Values.service.tcs.containerPort }}
      {{- if .Values.global }}
      nodePort: {{ .Values.global.service.tcs }}
      {{- else }}
      nodePort: {{ .Values.service.tcs.port }}
      {{- end }}