{{- include "factory.headers" . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.dependentServices.cms }}-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cms-init.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "cms-init.labels" . | nindent 8 }}
    spec:
      serviceAccountName: isecl
      initContainers:
        - name: wait-for-cms
          {{- include "factory.imageInitContainer" . | indent 10 }}
          env:
            - name: URL
              value: https://{{ .Values.dependentServices.cms }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.cms.containerPort }}/cms/v1/version
            - name: VERSION
              value: {{.Chart.AppVersion }}         
            - name: DEPEDENT_SERVICE_NAME
              value: {{ .Values.dependentServices.cms }}
            - name: COMPONENT
              value: {{ .Values.dependentServices.cms }}-init
      containers:
        - name: cms-tls-digest-aas-bootstrap-token
          image: gcr.io/cloud-builders/kubectl:latest
          command: ["/bin/sh", "-c"]
          args:
            - >
              echo starting &&
              POD_NAME=`kubectl get pod -l app.kubernetes.io/name={{ .Values.dependentServices.cms }} -n {{ .Release.Namespace }} -o name` &&
              echo $POD_NAME &&
              CMS_TLS_SHA384=`kubectl exec -n {{ .Release.Namespace }} --stdin $POD_NAME -- {{ .Values.dependentServices.cms }} tlscertsha384` &&
              echo $CMS_TLS_SHA384 &&
              kubectl create secret generic cms-tls-cert-sha384 -n {{ .Release.Namespace }} --from-literal=CMS_TLS_CERT_SHA384=$CMS_TLS_SHA384 &&
              AAS_TOKEN=`kubectl exec -n {{ .Release.Namespace }} --stdin $POD_NAME -- cms setup cms-auth-token --force | grep "JWT Token:" | awk '{print $3}'` &&
              echo $AAS_TOKEN &&
              kubectl create secret generic aas-token -n {{ .Release.Namespace }} --from-literal=BEARER_TOKEN=$AAS_TOKEN
      restartPolicy: Never
  backoffLimit: 4