{{- include "factory.headers" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "factory.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  AAS_ADMIN_USERNAME: {{ .Values.secret.adminUsername }}
  AAS_ADMIN_PASSWORD: {{ .Values.secret.adminPassword }}
  #TODO: the below db username and password need to move into their own db-secrets.yaml and be used from there
  AAS_DB_USERNAME: {{ .Values.secret.dbUsername }}
  AAS_DB_PASSWORD: {{ .Values.secret.dbPassword }}