{{- include "factory.headers" . }}
---
{{- include "factory.serviceCommonSpec" . }}
  type: NodePort
  ports:
    - port: {{ .Values.service.aas.containerPort }}
      targetPort: {{ .Values.service.aas.containerPort }}
      {{- if .Values.global }}
      nodePort: {{ .Values.global.service.aas }}
      {{- else }}
      nodePort: {{ .Values.service.aas.port }}
      {{- end }}