apiVersion: v2
name: TEE-Attestation
description: A Helm chart for Deploying TEE Attestation Use case

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v4.1.0"

dependencies:
  - name: factory
    repository: file://../../lib/factory/ 
    version: 0.1.0
  - name: cms
    repository: file://../../services/cms/ 
    version: 0.1.0
  - name: aas
    repository: file://../../services/aas/ 
    version: 0.1.0
  - name: aas-manager
    repository: file://../../jobs/aas-manager/ 
    version: 0.1.0
  - name: kbs
    repository: file://../../services/kbs/ 
    version: 0.1.0
  - name: qvs
    repository: file://../../services/qvs/ 
    version: 0.1.0
  - name: aps
    repository: file://../../services/aps/ 
    version: 0.1.0
  - name: tcs
    repository: file://../../services/tcs/ 
    version: 0.1.0
  - name: fda
    repository: file://../../services/fda/ 
    version: 0.1.0

maintainers:
- name: Om Prakash
  email: om.prakash.chaudhary@intel.com
- name: JJ
  email: johnny.jacob@intel.com
- name: PraveenRaj R
  email: praveenrajr@intel.com
- name: rana19
  email: raghavender.nagarajan@intel.com
