---
# The below section can be used to override additional values defined under each of the dependent charts
cms:
  image:
    name: <user input> # Certificate Management Service image name<br> (**REQUIRED**)

aas:
  image:
    name: <user input> # Authentication & Authorization Service image name<br> (**REQUIRED**)

aas-manager:
  image:
    name: <user input> # Authentication & Authorization Manager image name<br> (**REQUIRED**)

tcs:
  image:
    name: <user input> # TEE caching service image name<br> (**REQUIRED**)

qvs:
  image:
    name: <user input> # Quote Verification flow image name<br> (**REQUIRED**)

fda:
  image:
    name: <user input> # Feature Discovery Agent flow image name<br> (**REQUIRED**)

ta:
  image:
    name: <user input> # Trust Agent image name<br> (**REQUIRED**)

aps:
  image:
    name: <user input> # Attestation policy service image name<br> (**REQUIRED**)

kbs:
  image:
    name: <user input> # Key Broker Service flow image name<br> (**REQUIRED**)

global:
  controlPlaneHostname: <user input> # K8s control plane IP/Hostname<br> (**REQUIRED**)

  config:
    keyManager: kmip # The Key manager for KBS (Allowed values: `kmip`)
    kmip:       
      serverIp: <user input> # The KMIP server IP
      serverHostname: <user input> # The KMIP server hostname
      serverPort: <user input> # The KMIP server port
      clientCertPath: <user input> # The KMIP server client certificate absolute path
      clientKeyPath: <user input> # The KMIP server client key absolute path
      rootCertPath: <user input> # The KMIP server root certificate absolute path


  image:
    registry: <user input> # The image registry where isecl images are pushed<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry (Allowed values: `Always`/`IfNotPresent`)

  storage:
    nfs:
      server: <user input> # The NFS Server IP/Hostname<br> (**REQUIRED**)
      path: /mnt/nfs_share/  # The path for storing persistent data on NFS

  service:
    aas: 30444 # The service port for Authentication Authorization Service
    cms: 30445 # The service port for Certificate Management Service
    kbs: 30448 # The service port for Key broker service
    qvs: 30501 # The service port for Authentication Authorization Service
    tcs: 30502 # The service port for TCS Service
    aps: 30503 # The service port for Attestation policy service
