{{- include "factory.headers" . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fdsdb-cert-generator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fdsdb-cert-generator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "fdsdb-cert-generator.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext.fdsdbCertGeneratorInit | nindent 8 }}
      serviceAccountName: isecl
      restartPolicy: Never
      containers:
        - name: fdsdb-cert-generator-cfssl
          image: cfssl/cfssl:1.6.1
          imagePullPolicy: Always
          securityContext:
            {{- toYaml .Values.securityContext.fdsdbCertGenerator | nindent 12 }}
          command: ["/bin/sh", "-c"]
          args:
            - >
              echo Creating Database SSL Cert &&
              cd /tmp/ &&
              cfssl gencert -initca /tmp/certs/ca-csr.json | cfssljson -bare ca - &&
              echo '{"CN":"fdsdb TLS Certificate","hosts":["fdsdb.{{ .Release.Namespace }}.svc.cluster.local  "],"key":{"algo":"rsa","size":4096}}' | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -profile=server -hostname="fdsdb.{{ .Release.Namespace }}.svc.cluster.local" - | cfssljson -bare fdsdb-server
          volumeMounts:
            - name: ca-csr
              mountPath: /tmp/certs
        - name: fdsdb-cert-generator-kubectl
          image: bitnami/kubectl:1.22
          imagePullPolicy: Always
          securityContext:
            {{- toYaml .Values.securityContext.fdsdbCertGenerator | nindent 12 }}
          command: ["/bin/sh", "-c"]
          args:
            - >
              echo Storing SSL cert to k8s secrets &&
              cd /tmp/ &&
              kubectl create secret generic fdsdb-certs -n {{ .Release.Namespace }} --from-file=server.crt=fdsdb-server.pem --from-file=server.key=fdsdb-server-key.pem
          volumeMounts:
            - name: ca-csr
              mountPath: /tmp/certs
      volumes:
        - name: ca-csr
          configMap:
            name: ca-csr
