{{- include "factory.headers" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "factory.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  CMS_BASE_URL: https://{{.Values.dependentServices.cms}}-svc.isecl.svc.cluster.local:{{.Values.service.cms.containerPort }}/cms/v1/
  ENDPOINT_URL:  https://kbs-svc.isecl.svc.cluster.local:{{ .Values.service.kbs.containerPort }}/v1/
  AAS_API_URL: https://{{.Values.dependentServices.aas}}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.aas.containerPort }}/aas/v1/
  {{- if .Values.global }}
  TLS_SAN_LIST: {{ .Values.global.controlPlaneHostname }},{{ include "factory.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
  KEY_MANAGER: {{ .Values.global.config.keyManager }}
  KMIP_SERVER_IP: {{ .Values.global.config.kmip.serverIp }}
  KMIP_HOSTNAME: {{ .Values.global.config.kmip.serverHostname }}
  KMIP_SERVER_PORT: "{{ .Values.global.config.kmip.serverPort }}"
  KMIP_CLIENT_CERT_PATH: {{ .Values.global.config.kmip.clientCertPath }}
  KMIP_CLIENT_KEY_PATH: {{ .Values.global.config.kmip.clientKeyPath }}
  KMIP_ROOT_CERT_PATH: {{ .Values.global.config.kmip.rootCertPath }}
  {{- else }}
  TLS_SAN_LIST: {{ .Values.controlPlaneHostname }},{{ include "factory.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
  KEY_MANAGER: {{ .Values.config.keyManager }}
  KMIP_SERVER_IP: {{ .Values.config.kmip.serverIp }}
  KMIP_HOSTNAME: {{ .Values.config.kmip.serverHostname }}
  KMIP_SERVER_PORT: "{{ .Values.config.kmip.serverPort }}"
  KMIP_CLIENT_CERT_PATH: {{ .Values.config.kmip.clientCertPath }}
  KMIP_CLIENT_KEY_PATH: {{ .Values.config.kmip.clientKeyPath }}
  KMIP_ROOT_CERT_PATH: {{ .Values.config.kmip.rootCertPath }}
  {{- end }}