# Default values for hvs

nameOverride: "" # The name for HVS chart<br> (Default: `.Chart.Name`)
controlPlaneHostname: <user input> # K8s control plane IP/Hostname<br> (**REQUIRED**)

# Warning: Ensure that the naming is applied consistently for all dependent services when modifying nameOverride
# TODO: Services should be be able to be deployed in different namespaces
dependentServices: # The dependent Service Name for deploying  HVS chart, default is the chart name and override is from nameOverride value.
  cms: cms
  aas: aas

config:
  envVarPrefix: HVS
  dbPort: 5432 # PostgreSQL DB port
  dbSSL: on # PostgreSQL DB SSL<br> (Allowed Values: `on`/`off`)
  dbSSLCert: /etc/postgresql/secrets/server.crt # PostgreSQL DB SSL Cert
  dbSSLKey: /etc/postgresql/secrets/server.key  # PostgreSQL DB SSL Key
  dbSSLCiphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256 # PostgreSQL DB SSL Ciphers
  dbListenAddresses: "*" # PostgreSQL DB Listen Address
  dbName: hvsdb # HVS DB Name
  dbSSLMode: verify-full # PostgreSQL DB SSL Mode
  nats:
    enabled: false # Enable/Disable NATS mode<br> (Allowed values: `true`\`false`)
    servers: ""  # NATS Server IP/Hostname  
    serviceMode: "" # The model for TA<br> (Allowed values: `outbound`)
    
secret:
  dbUsername: hvsdbuser # DB Username for HVS DB
  dbPassword: hvsdbpassword # DB Password for HVS DB
  serviceUsername: hvsAdminUser # Admin Username for HVS
  servicePassword: hvsAdminPass # Admin Password for HVS

image:
  db:
    registry: dockerhub.io # The image registry where PostgreSQL image is pulled from
    name: postgres:11.7 # The image name of PostgreSQL
    pullPolicy: Always # The pull policy for pulling from container registry for PostgreSQL image
  svc:
    registry: <user input> # The image registry where HVS image is pushed<br> (**REQUIRED**)
    name: <user input> # The image name with which HVS image is pushed to registry<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry for HVS<br> (Allowed values: `Always`/`IfNotPresent`)

storage:
  nfs:
    server: <user input> # The NFS Server IP/Hostname<br> (**REQUIRED**)
    reclaimPolicy: Retain # The reclaim policy for NFS<br> (Allowed values: `Retain`/)
    accessModes: ReadWriteMany # The access modes for NFS<br> (Allowed values: `ReadWriteMany`)
    path: /mnt/nfs_share # The path for storing persistent data on NFS
    dbSize: 5Gi # The DB size for storing DB data for HVS in NFS path
    configSize: 10Mi # The configuration size for storing config for HVS in NFS path
    logsSize: 1Gi # The logs size for storing logs for HVS in NFS path
    baseSize: 6.1Gi # The base volume size (configSize + logSize + dbSize)

securityContext:
  hvsdbInit: # The fsGroup id for init containers for HVS DB
    fsGroup: 2000
  hvsdb: # The security content for HVS DB Service Pod
    runAsUser: 1001
    runAsGroup: 1001
  hvsInit: # The fsGroup id for init containers for HVS
    fsGroup: 1001
  hvs: # The security content for HVS Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false

service:
  directoryName: hvs
  cms:
    containerPort: 8445 # The containerPort on which CMS can listen
  aas: 
    containerPort: 8444 # The containerPort on which AAS can listen
    port: 30444 # The externally exposed NodePort on which AAS can listen to external traffic
  hvsdb:
    containerPort: 5432 # The containerPort on which HVS DB can listen 
  hvs:
    containerPort: 8443 # The containerPort on which HVS can listen 
    port: 30443 # The externally exposed NodePort on which HVS can listen to external traffic
