{{- include "factory.headers" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "factory.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  WLS_SERVICE_USERNAME: {{ .Values.secret.adminUsername }}
  WLS_SERVICE_PASSWORD: {{ .Values.secret.adminPassword }}
