# Default values for wlsdb-cert-generator.

nameOverride: "" # The name for AAS-MANAGER chart (Default: .Chart.Name)

securityContext:
  wlsdbCertGeneratorInit: # The fsGroup id for init containers for AAS DB
    fsGroup: 1001
  wlsdbCertGenerator: # The security content for AAS DB Service Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false