{{- include "factory.headers" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "factory.name" . }}
  namespace: {{ .Release.Namespace }}
data:
   CMS_BASE_URL: https://{{ .Values.dependentServices.cms }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.aps.containerPort }}/cms/v1
   AAS_BASE_URL: https://{{ .Values.dependentServices.aas }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.aas.containerPort }}/aas/v1
   QVS_BASE_URL: https://{{ .Values.dependentServices.qvs }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.qvs.containerPort }}/qvs/v1
   DB_VENDOR: {{ .Values.config.vender }}
   DB_HOST: localhost
   DB_USERNAME: {{ .Values.secret.dbUsername }}
   DB_PORT: {{ .Values.config.dbPort | quote }}
   DB_PASSWORD: {{ .Values.secret.dbPassword }}
   DB_NAME: {{ .Values.config.dbName }}
   DB_SSL_MODE: {{ .Values.config.dbSSLMode }}
   DB_SSL_CERT_SOURCE: {{ .Values.config.dbSSLCertSource }}
   TLS_SAN_LIST: {{ .Values.controlPlaneHostname }}
   APS_SERVICE_USERNAME: {{ .Values.secret.serviceUser }}
   APS_SERVICE_PASSWORD: {{ .Values.secret.servicePassord }}
   NO_PROXY: {{ .Values.controlPlaneHostname }},{{ include "factory.name" . }}
