{{- include "factory.headers" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "factory.name" . }}db-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  HVS_DB_USERNAME: {{ .Values.secret.dbUsername }}
  HVS_DB_PASSWORD: {{ .Values.secret.dbPassword }}