# Default values for cleanup-secrets.

nameOverride: "" # The name for CLEANUP-SECRETS chart (Default: .Chart.Name)

securityContext:
  cleanupSecretsInit: # The fsGroup id for init containers for AAS DB
    fsGroup: 1001
  cleanupSecrets: # The security content for AAS DB Service Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false